.\" This file is distributed under the same license as the mentohust package.
.\" Copyright (C) 2009 HustMoon <mentohust@ehust.co.cc>.
.\"
.TH MENTOHUST 1 "2009-12-03"

.SH NAME
mentohust \- A Ruijie and Cernet supplicant on Linux and MacOS

.SH SYNOPSIS
.B mentohust
[-option][value] ...

.SH DESCRIPTION
.PP
mentohust is a Ruijie and Cernet supplicant on Linux and MacOS.
.br
See \fI/usr/share/doc/mentohust/README\fR for more information.

.PP
Type
.B mentohust -h
and see \fI/usr/share/doc/mentohust/README\fR for usage.

.PP
Homepage: http://mentohust.googlecode.com/
.br
E-mail: mentohust@ehust.co.cc

.SH AUTHOR
.PP
mentohust was written by HustMoon <www.ehust@gmail.com>
.br
and kkHAIKE <kkHAIKE@gmail.com>.
.br
This manual page was written by HustMoon <www.ehust@gmail.com>.
